### ISSUE TITLE
Out of range panic on query

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ds-bolt#5]
```
...

=== RUN   TestSuite/github.com/ipfs/go-datastore/test.SubtestCombinations/1/{SELECT·keys,vals·FILTER·[KEY·==·"/0key0"]·ORDER·[desc(KEY)]}
=== RUN   TestSuite/github.com/ipfs/go-datastore/test.SubtestCombinations/1/{SELECT·keys,vals·FILTER·[KEY·==·"/0key0"]·ORDER·[desc(KEY)]·OFFSET·10}
panic: runtime error: slice bounds out of range [10:1]

goroutine 3583 [running]:
github.com/ipfs/go-ds-bolt.(*BoltDatastore).Query.func1.1(0xc0000f4460, 0x0, 0x0)
	/home/michael/dev/go-ds-bolt/datastore.go:156 +0x1508
github.com/boltdb/bolt.(*DB).View(0xc0000f0000, 0xc000117ef0, 0x0, 0x0)
	/home/michael/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:629 +0x14c
github.com/ipfs/go-ds-bolt.(*BoltDatastore).Query.func1(0x6854c0, 0xc000220de0)
	/home/michael/dev/go-ds-bolt/datastore.go:121 +0x169
github.com/jbenet/goprocess.(*process).Go.func1(0xc0000c1b00, 0xc000220de0, 0xc000220e40)
	/home/michael/go/pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:134 +0x41
created by github.com/jbenet/goprocess.(*process).Go
	/home/michael/go/pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:133 +0xda

```

**Comment by bonedaddy** [comment]
Any idea whats' causing this? I'm running into this issue as well and it's stumped me. I tried changing the problematic line to:

```
				// offset/limit
				if len(entries) >= q.Offset {
					entries = entries[q.Offset:]
				}
				if q.Limit > 0 && q.Limit < len(entries) {
					entries = entries[:q.Limit]
				}
```

and that causes tests to fail

**Comment by Stebalien** [comment]
I haven't had time to debug this. We don't use this datastore in go-ipfs so it's not very high on the "to fix" list.
